### ISSUE TITLE
Checks not reporting after report uploaded in GitHub Action

### ISSUE THREAD

**Issue by ajcann** [packtracker/report#6]
GitHub Check reports "We're waiting to process the stats for the latest commit for this pull request."

The GitHub Action logs shows: 
```
packtracker: webpack config file loaded (./client/webpack.config.js)
packtracker: loading github config
packtracker: instantiate plugin
packtracker: configured successfully
(node:122) DeprecationWarning: Tapable.plugin is deprecated. Use new API on `.hooks` instead
Webpack Bundle Analyzer saved report to /github/workspace/dist/static/report.html
packtracker: webpack build succeeded
HEAD is now at e261d467 Enable packtracker and switch to alpine image
Removing dist/
Removing node_modules/
Removing report.js
```

Packtracker has worked with this general configuration as a dev dependency. We're testing removing that dependency and allowing the Action to perform this function. report.html is being generated. Our Actions looks as so (secrets have been added):

```
on: push
name: packtracker.io
jobs:
  report:
    name: report webpack stats
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: Build assets
        run: |
          echo "//npm.pkg.github.com/:_authToken=${{ secrets.GPR_TOKEN }}" >> .npmrc
          yarn --frozen-lockfile
          NODE_ENV=production yarn build
      - name: report webpack stats
        uses: packtracker/report@2.2.7
        env:
          PT_PROJECT_TOKEN: ${{ secrets.PT_PROJECT_TOKEN }}
          WEBPACK_CONFIG_PATH: ./client/webpack.config.js
```

Thanks for any help!
